# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/8211600/Desktop/APS/RISC-V_SNA/trunk/project/RISC-V_SNA.cache/wt [current_project]
set_property parent.project_path C:/Users/8211600/Desktop/APS/RISC-V_SNA/trunk/project/RISC-V_SNA.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/8211600/Desktop/APS/RISC-V_SNA/trunk/project/RISC-V_SNA.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem C:/Users/8211600/Desktop/APS/RISC-V_SNA/trunk/src/sv/program.txt
read_verilog -library xil_defaultlib -sv {
  C:/Users/8211600/Desktop/APS/RISC-V_SNA/trunk/src/sv/PC.sv
  C:/Users/8211600/Desktop/APS/RISC-V_SNA/trunk/src/sv/alu_opcodes_pkg.sv
  C:/Users/8211600/Desktop/APS/RISC-V_SNA/trunk/src/sv/alu_riscv.sv
  C:/Users/8211600/Desktop/APS/RISC-V_SNA/trunk/src/sv/fulladder.sv
  C:/Users/8211600/Desktop/APS/RISC-V_SNA/trunk/src/sv/fulladder32.sv
  C:/Users/8211600/Desktop/APS/RISC-V_SNA/trunk/src/sv/fulladder4.sv
  C:/Users/8211600/Desktop/APS/RISC-V_SNA/trunk/src/sv/fulladder_usk.sv
  C:/Users/8211600/Desktop/APS/RISC-V_SNA/trunk/src/sv/instr_mem.sv
  C:/Users/8211600/Desktop/APS/RISC-V_SNA/trunk/src/sv/rf_riscv.sv
  C:/Users/8211600/Desktop/APS/RISC-V_SNA/trunk/src/sv/CYBERcobra.sv
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top CYBERcobra -part xc7k70tfbv676-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CYBERcobra.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CYBERcobra_utilization_synth.rpt -pb CYBERcobra_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
