@echo off
REM ****************************************************************************
REM Vivado (TM) v2019.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Oct 26 00:33:25 +0300 2023
REM SW Build 2708876 on Wed Nov  6 21:40:23 MST 2019
REM
REM Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
echo "xsim tb_decoder_riscv_behav -key {Behavioral:sim_1:Functional:tb_decoder_riscv} -tclbatch tb_decoder_riscv.tcl -view D:/MIET/8211600/APS/RISC-V_SNA/trunk/project/tb_CYBERcobra_behav.wcfg -log simulate.log"
call xsim  tb_decoder_riscv_behav -key {Behavioral:sim_1:Functional:tb_decoder_riscv} -tclbatch tb_decoder_riscv.tcl -view D:/MIET/8211600/APS/RISC-V_SNA/trunk/project/tb_CYBERcobra_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
