webtalk_init -webtalk_dir D:/MIET/8211600/APS/RISC-V_SNA/trunk/project/RISC-V_SNA.sim/sim_1/behav/xsim/xsim.dir/tb_rf_riscv_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Oct 13 20:52:21 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "9d1939eb-35eb-46a5-8383-ad4f26197c4f" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e3c253f7859e48db897d3ba5a8deba43" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6328_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3130022479 -regid "" -xml D:/MIET/8211600/APS/RISC-V_SNA/trunk/project/RISC-V_SNA.sim/sim_1/behav/xsim/xsim.dir/tb_rf_riscv_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/MIET/8211600/APS/RISC-V_SNA/trunk/project/RISC-V_SNA.sim/sim_1/behav/xsim/xsim.dir/tb_rf_riscv_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/MIET/8211600/APS/RISC-V_SNA/trunk/project/RISC-V_SNA.sim/sim_1/behav/xsim/xsim.dir/tb_rf_riscv_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
